spring:
  application:
    name: confero-api
  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      max-lifetime: 80000
      idle-timeout: 10000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

supabase.jwt.secret: secret

orcid:
  client-id: client-id
  client-secret: client-secret
  redirect-uri: redirect-uri
  auth-url: https://orcid.org/oauth/authorize
  token-url: https://orcid.org/oauth/token