spring:
  application:
    name: confero-api

  jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:confero}?prepareThreshold=0
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      max-lifetime: 120000
      idle-timeout: 10000
      maximum-pool-size: 40

  mail:
    host: smtp.gmail.com
    port: 465
    username: confero.contact@gmail.com
    password: ${MAIL_PASS:secret}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
logging:
  level:
    feign:
      client:
        OrcidClient: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    enabled: false

server:
  servlet:
    context-path: /api


supabase:
  jwt:
    secret: ${SUPABASE_JWT_SECRET:secret}
  s3:
    endpoint: https://yerxopcahxybrxkyxayf.supabase.co/storage/v1/s3
    access-key: ${S3_ACCESS_KEY:a5b648d8c709452fb03520ffc596b710}
    secret-key: ${S3_SECRET_KEY:secret-key}
    bucket: confero

orcid:
  client-id: APP-O78NWU9RUK7WPFEH
  client-secret: ${ORCID_CLIENT_SECRET:secret}
  redirect-uri: ${ORCID_REDIRECT_URI:https://627b-178-37-12-53.ngrok-free.app/api/auth/orcid/callback}
  auth-url: https://orcid.org/oauth/authorize
  token-url: https://orcid.org/oauth/token

redirect:
  base-url:
    http://localhost:5173


email:
  verification:
    base-url: http://localhost:8080