spring:
  application:
    name: confero-api

  datasource:
    url: jdbc:postgresql://localhost:5432/confero
    username: ${DB_USER:postgres}
    password: ${DB_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    feign:
      client:
        OrcidClient: DEBUG

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    enabled: false

server:
  servlet:
    context-path: /api


supabase.jwt.secret: ${SUPABASE_JWT_SECRET:secret}

orcid:
  client-id: APP-O78NWU9RUK7WPFEH
  client-secret: ${ORCID_CLIENT_SECRET:secret}
  redirect-uri: https://b252-77-254-238-252.ngrok-free.app/api/auth/orcid/callback
  auth-url: https://orcid.org/oauth/authorize
  token-url: https://orcid.org/oauth/token