services:
  confero-api:
    container_name: confero-api
    env_file:
      - .env
    build:
      context: ./confero-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
  confero-ui:
    container_name: confero-ui
    build:
      context: ./
      dockerfile: ./confero-ui/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt