services:
  postgres:
    image: postgres:latest
    container_name: confero-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: confero
    restart: always
    ports:
      - "5434:5432"
  confero-api:
    container_name: confero-api
    environment:
        DB_HOST: postgres
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        MAIL_PASS: ${MAIL_PASS}
        SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
        ORCID_CLIENT_SECRET: ${ORCID_CLIENT_SECRET}
        SPRING_PROFILES_ACTIVE: dev
    build:
      context: ./confero-api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  confero-ui:
    container_name: confero-ui
    build:
      context: ./
      dockerfile: ./confero-ui/Dockerfile
    restart: always
    ports:
      - "80:80"