version: '3.8'

services:
  confero-api:
    container_name: confero-api
    env_file:
      - .env
    build:
      context: ./confero-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224" # Use Fluentd container name
        tag: "confero-api"

  confero-ui:
    container_name: confero-ui
    build:
      context: ./
      dockerfile: ./confero-ui/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224" # Use Fluentd container name
        tag: "confero-ui"

  fluentd:
    container_name: fluentd
    image: fluent/fluentd:v1.14-1
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"  # Fluentd default port for incoming logs
      - "24225:24225"  # Optional HTTP interface (if configured)
