services:
  postgres:
    image: postgres:latest
    container_name: confero-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: confero
    restart: always
    ports:
      - "5434:5432"
  confero-api:
    container_name: confero-api
    build:
      context: ./confero-api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
  confero-ui:
    container_name: confero-ui
    build:
      context: ./
      dockerfile: ./confero-ui/Dockerfile
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env