services:
  confero-api:
    container_name: confero-api
    env_file:
      - .env
    build:
      context: ./confero-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "confero-api"
  confero-ui:
    container_name: confero-ui
    build:
      context: ./
      dockerfile: ./confero-ui/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  fluentd:
    container_name: fluentd
    image: fluent/fluentd:v1.14-1
    ports:
      - "24224:24224"
      - "24225:24225"