name: UI Build Check
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Navigate to project directory and install dependencies
        run: |
          cd confero-ui
          npm install

      - name: Build the project
        run: |
          cd confero-ui
          npm run build
